version: '3.9'

services:
  redis:
    image: 'redis:latest'
    container_name: redis
    ports:
      - '6379:6379'
    command: [ "redis-server" ]
  #      volumes:
  #        - ./redis.conf:/etc/redis/redis.conf
  keycloak:
    image: quay.io/keycloak/keycloak:22.0.3
    ports:
      - "8080:8080"
    environment:
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=admin
      - DEBUG=true
      - DB_VENDOR=POSTGRES
      - DB_ADDR=postgres
      - DB_PORT=5432
      - DB_DATABASE=dev
      - DB_USER=postgres
      - DB_PASSWORD=phale50
    depends_on:
      - postgres
    command:
      - start-dev
    volumes:
      - ./auth/import:/opt/keycloak/data/import
    networks:
      - backend

  postgres:
    image: postgres:15.5-alpine3.19
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: dev
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: phale50
    ports:
      - "5432:5432"
    networks:
      - backend

  zookeeper:
    container_name: vitech_zookeeper_local
    image: confluentinc/cp-zookeeper:latest
    ports:
      - 2181:2181
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
    networks:
      - backend

  kafka:
    container_name: vitech_kafka_local
    image: confluentinc/cp-kafka:latest
    depends_on:
      - zookeeper
    environment:
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
#      KAFKA_ADVERTISED_HOST_NAME: localhost
#      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:29092,PLAINTEXT_INTERNAL://vitech_kafka:29093
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://127.0.0.1:29092,PLAINTEXT_INTERNAL://127.0.0.1:29093
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_INTERNAL:PLAINTEXT
      KAFKA_CREATE_TOPICS: "user-activity:1:2,exception:1:2"
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
    ports:
      - "29092:29092"
      - "29093:29093"
    networks:
      - backend

  # command:
  #kafka-topics --create --bootstrap-server localhost:29092 --replication-factor 1 --partitions 1 --topic TutorialTopic
  # kafka-topics --delete --topic TutorialTopic --bootstrap-server localhost:29092

networks:
  backend:
    name: backend
    driver: bridge

volumes:
  postgres_data:
    driver: local
