server:
  port: ${PORT_SERVER:9001}
---
#spring:
#  security:
#    oauth2:
#      resource-server:
#        jwt:
#          jwk-set-uri: ${KEYCLOAK_HOST:http://localhost:8080}/realms/${KEYCLOAK_REALM:vitech-shopping}/protocol/openid-connect/certs
---
spring:
  datasource:
    url: ${JDBC_URL:jdbc:postgresql://localhost:5432/dev?escapeSyntaxCallMode=callIfNoReturn}
    username: ${JDBC_USERNAME:postgres}
    password: ${JDBC_PASSWORD:phale50}
---
spring:
  datasource:
    hikari:
      connection-timeout: 20000
      idle-timeout: 300000
      max-lifetime: 1800000
      minimum-idle: 10
      maximum-pool-size: 20
      auto-commit: true
---
spring:
  application:
    name: ${HOSTNAME:shopping-service}
eureka: #<1>
  instance:
    app-name: ${HOSTNAME:shopping-service}
    lease-renewal-interval-in-seconds: 5
    lease-expiration-duration-in-seconds: 5
    health-check-url-path: /actuator/health
    metadata-map:
      startup: ${random.int}    #needed to trigger info and endpoint update after restart
  client:
    initial-instance-info-replication-interval-seconds: 5
    registry-fetch-interval-seconds: 5
    serviceUrl:
      defaultZone: ${EUREKA_SERVICE_URL:http://localhost:8761}/eureka/
    enabled: true
    register-with-eureka: true
    fetch-registry: true
    healthcheck:
      enabled: true

---
eureka:
  instance:
    ip-address: ${CLIENT_IP_ADDRESS:localhost}
    prefer-ip-address: ${PREFER_IP_ADDRESS:false}
    hostname: ${HOSTNAME:shopping-service}

---
spring:
  mvc:
    dispatch-options-request: true
---
keycloak:
  realm-master: ${KEYCLOAK_REALM_ADMIN:master}
  realm: ${KEYCLOAK_REALM:vitech-shopping}
  auth-server-url: ${KEYCLOAK_HOST:http://localhost:8080}
  client-admin: ${KEYCLOAK_CLIENT_ADMIN:admin-cli}
  client: ${KEYCLOAK_CLIENT:vitech-shopping}
  credentials:
    client-id: admin-cli
    username: ${KEYCLOAK_USERNAME:admin}
    password: ${KEYCLOAK_PASSWORD:admin}
---
logging:
  level:
    com:
      zaxxer:
        hikari: INFO
---
spring:
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${MAIL_USERNAME:truongquocviet2001@gmail.com}
    password: ${MAIL_PASSWORD:typm nhve deee hjlz}
    #    protocol: smtp
    properties:
      mail:
        smtp:
          starttls:
            enable: true
          auth: true
          connection-timeout: ${MAIL_CONNECTION_TIMEOUT:30000}
          timeout: ${MAIL_CONNECTION_TIMEOUT:30000}
          write timeout: ${MAIL_CONNECTION_TIMEOUT:30000}
          ssl:
            enable: false
    default-encoding: UTF-8
---
spring:
  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}
---
springdoc:
  swagger-ui:
    path: /index.html
---
token:
  signin:
    key: ${TOKEN_SIGNIN_KEY:413F4428472B4B6250655368566D5970337336763979244226452948404D6351213421312312312321312awdfada}
---
spring:
  kafka:
    bootstrap-servers: ${BOOTSTRAP_SERVERS:localhost:29092}
    producer:
      key-serializer: ${KEY_SERIALIZER:org.apache.kafka.common.serialization.StringSerializer}
      value-serializer: ${VALUE_SERIALIZER:org.springframework.kafka.support.serializer.JsonSerializer}
    template:
      default-topic: ${DEFAULT_TOPIC:order-statistic}
